### PR TITLE
fix(tvshow): make episode number nullable

### LINKED ISSUE #63: `TVShow::number_of_episodes` is nullable
Tested on `/3/tv/81040`, the API returns `null` for `number_of_episodes`, which causes the client failed to deserialize.

### PR DESCRIPTION
**Pull request by agmbk**
Fixes #63

### CODE REVIEW

File: src/tvshow/mod.rs [hunk 1]
```diff
@@ -120,6 +120,7 @@ pub struct TVShow {
     pub last_episode_to_air: Option<EpisodeShort>,
     pub next_episode_to_air: Option<EpisodeShort>,
     pub networks: Vec<CompanyShort>,
+    #[serde(deserialize_with = "crate::util::default_on_null::deserialize")]
     pub number_of_episodes: u64,
```
Comment (jdrouet) [inline src/tvshow/mod.rs:124]: I've my doubt on this. I think I'd prefer making it optional to keep the idea that it was not specified

**Review by jdrouet — CHANGES_REQUESTED** [review]
I think marking this as optional should be enough

File: src/tvshow/mod.rs (hunk 1 above)
Comment (agmbk) [reply src/tvshow/mod.rs:124]: Right since the tv show effectively have one episode, I didn't check that. A bit disappointing to complexify the data flow for such edge cases

**Review by jdrouet — APPROVED** [review]
